import '@radix-ui/themes/styles.css'
import './theme-config.css'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'
import AuthProvider from './auth/AuthProvider'
import { Container, Theme } from '@radix-ui/themes'

const inter = Inter({ subsets: ['latin'], display: 'swap', variable: '--font-inter' })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.variable}>
                <AuthProvider>
                    <Theme accentColor="violet">
                        <NavBar />
                        <main className=" p-5">
                            <Container>{children}</Container>
                        </main>
                    </Theme>
                </AuthProvider>
            </body>
        </html>
    )
}
